# Generated by Django 4.2.14 on 2024-07-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
